#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
# autospec version: v3
# autospec commit: c1050fe
#
Name     : btop
Version  : 1.2.13
Release  : 7
URL      : https://github.com/aristocratos/btop/archive/v1.2.13/btop-1.2.13.tar.gz
Source0  : https://github.com/aristocratos/btop/archive/v1.2.13/btop-1.2.13.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: btop-bin = %{version}-%{release}
Requires: btop-data = %{version}-%{release}
Requires: btop-license = %{version}-%{release}
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# ![btop++](Img/logo.png)
<a href="https://repology.org/project/btop/versions">
<img src="https://repology.org/badge/vertical-allrepos/btop.svg" alt="Packaging status" align="right">
</a>

%package bin
Summary: bin components for the btop package.
Group: Binaries
Requires: btop-data = %{version}-%{release}
Requires: btop-license = %{version}-%{release}

%description bin
bin components for the btop package.


%package data
Summary: data components for the btop package.
Group: Data

%description data
data components for the btop package.


%package license
Summary: license components for the btop package.
Group: Default

%description license
license components for the btop package.


%prep
%setup -q -n btop-1.2.13
cd %{_builddir}/btop-1.2.13

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1701938618
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
make  %{?_smp_mflags}


%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1701938618
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/btop
cp %{_builddir}/btop-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/btop/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
%make_install PREFIX=/usr

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/btop

%files data
%defattr(-,root,root,-)
/usr/share/applications/btop.desktop
/usr/share/btop/README.md
/usr/share/btop/themes/HotPurpleTrafficLight.theme
/usr/share/btop/themes/adapta.theme
/usr/share/btop/themes/ayu.theme
/usr/share/btop/themes/dracula.theme
/usr/share/btop/themes/dusklight.theme
/usr/share/btop/themes/elementarish.theme
/usr/share/btop/themes/everforest-dark-hard.theme
/usr/share/btop/themes/flat-remix-light.theme
/usr/share/btop/themes/flat-remix.theme
/usr/share/btop/themes/greyscale.theme
/usr/share/btop/themes/gruvbox_dark.theme
/usr/share/btop/themes/gruvbox_dark_v2.theme
/usr/share/btop/themes/gruvbox_material_dark.theme
/usr/share/btop/themes/kyli0x.theme
/usr/share/btop/themes/matcha-dark-sea.theme
/usr/share/btop/themes/monokai.theme
/usr/share/btop/themes/night-owl.theme
/usr/share/btop/themes/nord.theme
/usr/share/btop/themes/onedark.theme
/usr/share/btop/themes/paper.theme
/usr/share/btop/themes/solarized_dark.theme
/usr/share/btop/themes/solarized_light.theme
/usr/share/btop/themes/tokyo-night.theme
/usr/share/btop/themes/tokyo-storm.theme
/usr/share/btop/themes/tomorrow-night.theme
/usr/share/btop/themes/whiteout.theme
/usr/share/icons/hicolor/48x48/apps/btop.png
/usr/share/icons/hicolor/scalable/apps/btop.svg

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/btop/2b8b815229aa8a61e483fb4ba0588b8b6c491890
